mutation {
	addCity(input: [{
		name: "miami"
    lat: 25.7617
    lng:-80.1918
	}])
	{
		city {
			id
		}
	}
}

mutation {
	updateCity(input: {
    filter: {id: ["0x3"] }
    set: {
      name: "miami-dade"
    }
  })
	{
    city {
      id
      name
      lat
      lng
    }
  }
}

mutation {
	deleteCity(filter: {id: ["0x3"] })
	{
    city {
      id
      name
      lat
      lng
    }
    msg
  }
}

query {
	getCity(id: "0x2" )
	{
    id
    name
    lat
    lng
  }
}

query {
	queryCity(filter: {	name: { eq: "new york" } })
	{
    id
    name
    lat
    lng
  }
}

mutation {
  updateCity(input: {
    filter: {
      id: ["0x3"]
    }
    set: {
      weather: {
        id: "0x4"
      }
    }
  }
  ) {
		city {
			id
      weather {
        id
        description
        city_name
        temp
        temp_min
        temp_max
      }
		}
	}
}

query {
	getWeather(id: "0x4" )
	{
    id
    description
    city_name
    temp
    temp_min
    temp_max
  }
}

mutation {
  deleteWeather(filter: {
      id: ["0x4"]
  }) {
    weather {
      id
		}
    msg
	}
}

mutation {
	addWeather(input: [{
		 city_name: "miami"
      description: "desc"
      pressure: 1034
      temp: 87.9
      temp_min: 67.9
      temp_max: 99.6
	}])
	{
		weather {
			id
		}
	}
}

mutation {
	addCity(input: [{
		name: "miami"
    lat: 25.7617
    lng:-80.1918
    weather: {
      city_name: "miami"
      description: "desc"
      pressure: 1034
      temp: 87.9
      temp_min: 67.9
      temp_max: 99.6
    }
	}])
	{
		city {
			id
      weather {
        id
      }
		}
	}
}

mutation {
	addPlace(input: [{
    address: "123 mocking bird"
    avg_user_rating: 5.0
    category: "bar"
    city: {
      id: "0x2"
    }
    name: "bill's rockin bar"
	}])
	{
		place {
			id
		}
	}
}

// ==================================================

directive @search(by: [DgraphIndex!]) on FIELD_DEFINITION
directive @dgraph(
  type: String
  pred: String
) on OBJECT | INTERFACE | FIELD_DEFINITION
directive @id on FIELD_DEFINITION
directive @secret(field: String!, pred: String) on OBJECT | INTERFACE
directive @hasInverse(field: String!) on FIELD_DEFINITION
directive @custom(http: CustomHTTP, dql: String) on FIELD_DEFINITION
directive @cascade on FIELD
directive @withSubscription on OBJECT | INTERFACE
directive @auth(
  query: AuthRule
  add: AuthRule
  update: AuthRule
  delete: AuthRule
) on OBJECT
directive @remote on OBJECT | INTERFACE
input AddCityInput {
  name: String!
  lat: Float!
  lng: Float!
  weather: WeatherRef
  places: [PlaceRef]
}

type AddCityPayload {
  city(filter: CityFilter, order: CityOrder, first: Int, offset: Int): [City]
  numUids: Int
}

input AddPlaceInput {
  address: String
  avg_user_rating: Float
  category: String
  city: CityRef!
  name: String!
}

type AddPlacePayload {
  place(
    filter: PlaceFilter
    order: PlaceOrder
    first: Int
    offset: Int
  ): [Place]
  numUids: Int
}

input AddWeatherInput {
  city_name: String!
  description: String
  pressure: Int
  temp: Float
  temp_min: Float
  temp_max: Float
}

type AddWeatherPayload {
  weather(
    filter: WeatherFilter
    order: WeatherOrder
    first: Int
    offset: Int
  ): [Weather]
  numUids: Int
}

input AuthRule {
  and: [AuthRule]
  or: [AuthRule]
  not: AuthRule
  rule: String
}

type City {
  id: ID!
  name: String!
  lat: Float!
  lng: Float!
  weather(filter: WeatherFilter): Weather
  places(
    filter: PlaceFilter
    order: PlaceOrder
    first: Int
    offset: Int
  ): [Place]
}

input CityFilter {
  id: [ID!]
  name: StringExactFilter
  has: CityHasFilter
  and: CityFilter
  or: CityFilter
  not: CityFilter
}

enum CityHasFilter {
  name
  lat
  lng
  weather
  places
}

input CityOrder {
  asc: CityOrderable
  desc: CityOrderable
  then: CityOrder
}

enum CityOrderable {
  name
  lat
  lng
}

input CityPatch {
  name: String
  lat: Float
  lng: Float
  weather: WeatherRef
  places: [PlaceRef]
}

input CityRef {
  id: ID
  name: String
  lat: Float
  lng: Float
  weather: WeatherRef
  places: [PlaceRef]
}

input CustomHTTP {
  url: String!
  method: HTTPMethod!
  body: String
  graphql: String
  mode: Mode
  forwardHeaders: [String!]
  secretHeaders: [String!]
  introspectionHeaders: [String!]
  skipIntrospection: Boolean
}

scalar DateTime

input DateTimeFilter {
  eq: DateTime
  le: DateTime
  lt: DateTime
  ge: DateTime
  gt: DateTime
}

type DeleteCityPayload {
  city(filter: CityFilter, order: CityOrder, first: Int, offset: Int): [City]
  msg: String
  numUids: Int
}

type DeletePlacePayload {
  place(
    filter: PlaceFilter
    order: PlaceOrder
    first: Int
    offset: Int
  ): [Place]
  msg: String
  numUids: Int
}

type DeleteWeatherPayload {
  weather(
    filter: WeatherFilter
    order: WeatherOrder
    first: Int
    offset: Int
  ): [Weather]
  msg: String
  numUids: Int
}

enum DgraphIndex {
  int
  int64
  float
  bool
  hash
  exact
  term
  fulltext
  trigram
  regexp
  year
  month
  day
  hour
}

input FloatFilter {
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
}

enum HTTPMethod {
  GET
  POST
  PUT
  PATCH
  DELETE
}

scalar Int64

input Int64Filter {
  eq: Int64
  le: Int64
  lt: Int64
  ge: Int64
  gt: Int64
}

input IntFilter {
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
}

enum Mode {
  BATCH
  SINGLE
}

type Mutation {
  addCity(input: [AddCityInput!]!): AddCityPayload
  updateCity(input: UpdateCityInput!): UpdateCityPayload
  deleteCity(filter: CityFilter!): DeleteCityPayload
  addPlace(input: [AddPlaceInput!]!): AddPlacePayload
  updatePlace(input: UpdatePlaceInput!): UpdatePlacePayload
  deletePlace(filter: PlaceFilter!): DeletePlacePayload
  addWeather(input: [AddWeatherInput!]!): AddWeatherPayload
  updateWeather(input: UpdateWeatherInput!): UpdateWeatherPayload
  deleteWeather(filter: WeatherFilter!): DeleteWeatherPayload
}

type Place {
  id: ID!
  address: String
  avg_user_rating: Float
  category: String
  city(filter: CityFilter): City!
  name: String!
}

input PlaceFilter {
  id: [ID!]
  category: StringExactFilter
  name: StringExactFilter
  has: PlaceHasFilter
  and: PlaceFilter
  or: PlaceFilter
  not: PlaceFilter
}

enum PlaceHasFilter {
  address
  avg_user_rating
  category
  city
  name
}

input PlaceOrder {
  asc: PlaceOrderable
  desc: PlaceOrderable
  then: PlaceOrder
}

enum PlaceOrderable {
  address
  avg_user_rating
  category
  name
}

input PlacePatch {
  address: String
  avg_user_rating: Float
  category: String
  city: CityRef
  name: String
}

input PlaceRef {
  id: ID
  address: String
  avg_user_rating: Float
  category: String
  city: CityRef
  name: String
}

type Query {
  getCity(id: ID!): City
  queryCity(
    filter: CityFilter
    order: CityOrder
    first: Int
    offset: Int
  ): [City]
  getPlace(id: ID!): Place
  queryPlace(
    filter: PlaceFilter
    order: PlaceOrder
    first: Int
    offset: Int
  ): [Place]
  getWeather(id: ID!): Weather
  queryWeather(
    filter: WeatherFilter
    order: WeatherOrder
    first: Int
    offset: Int
  ): [Weather]
}

input StringExactFilter {
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
}

input StringFullTextFilter {
  alloftext: String
  anyoftext: String
}

input StringHashFilter {
  eq: String
}

input StringRegExpFilter {
  regexp: String
}

input StringTermFilter {
  allofterms: String
  anyofterms: String
}

input UpdateCityInput {
  filter: CityFilter!
  set: CityPatch
  remove: CityPatch
}

type UpdateCityPayload {
  city(filter: CityFilter, order: CityOrder, first: Int, offset: Int): [City]
  numUids: Int
}

input UpdatePlaceInput {
  filter: PlaceFilter!
  set: PlacePatch
  remove: PlacePatch
}

type UpdatePlacePayload {
  place(
    filter: PlaceFilter
    order: PlaceOrder
    first: Int
    offset: Int
  ): [Place]
  numUids: Int
}

input UpdateWeatherInput {
  filter: WeatherFilter!
  set: WeatherPatch
  remove: WeatherPatch
}

type UpdateWeatherPayload {
  weather(
    filter: WeatherFilter
    order: WeatherOrder
    first: Int
    offset: Int
  ): [Weather]
  numUids: Int
}

type Weather {
  id: ID!
  city_name: String!
  description: String
  pressure: Int
  temp: Float
  temp_min: Float
  temp_max: Float
}

input WeatherFilter {
  id: [ID!]
  has: WeatherHasFilter
  and: WeatherFilter
  or: WeatherFilter
  not: WeatherFilter
}

enum WeatherHasFilter {
  city_name
  description
  pressure
  temp
  temp_min
  temp_max
}

input WeatherOrder {
  asc: WeatherOrderable
  desc: WeatherOrderable
  then: WeatherOrder
}

enum WeatherOrderable {
  city_name
  description
  pressure
  temp
  temp_min
  temp_max
}

input WeatherPatch {
  city_name: String
  description: String
  pressure: Int
  temp: Float
  temp_min: Float
  temp_max: Float
}

input WeatherRef {
  id: ID
  city_name: String
  description: String
  pressure: Int
  temp: Float
  temp_min: Float
  temp_max: Float
}
