version: '3.8'

networks:
  shared-network:
    driver: bridge

services:

  dgraph-zero:
    container_name: dgraph-zero
    networks:
      - shared-network
    image: dgraph/dgraph:master
    command: dgraph zero

  dgraph-alpha:
    container_name: dgraph-alpha
    networks:
      - shared-network
    image: dgraph/dgraph:master
    ports:
      - 8080:8080
    depends_on:
      - dgraph-zero
    command: dgraph alpha --vmodule=server=3

  service:
    container_name: service
    networks:
      - shared-network
    image: class-service-amd64:1.0
    ports:
      - 3000:3000 # API
    depends_on:
      - dgraph-alpha